# Generated by Django 3.1.6 on 2021-02-12 10:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Realtor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='photos/%Y%M%D/')),
                ('description', models.TextField(blank=True)),
                ('email', models.CharField(max_length=200)),
                ('is_mvp', models.BooleanField()),
                ('phone', models.CharField(max_length=20)),
                ('hire_date', models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 12, 16, 24, 29, 493748))),
            ],
        ),
    ]
